-- =========================================================================
-- MIGRATION 02 — Normalize types (text → DATE / TINYINT / YEAR / VARCHAR)
-- =========================================================================
-- - Columnas booleanas text("0"/"1") → TINYINT(1)
-- - Fechas text → DATE
-- - Años text(mixto) → normalizar a YEAR (para los que son fechas, extraer año)
-- - TEXT sobredimensionados en campos cortos → VARCHAR razonable
-- =========================================================================

USE censo_animales;

SET FOREIGN_KEY_CHECKS=0;

-- ---------- ANIMALES ----------
-- Booleanos: antes text con "0"/"1"
ALTER TABLE `ANIMALES`
  MODIFY `PESA_MAS_DE_20_KG` TINYINT(1) DEFAULT NULL,
  MODIFY `ESTERILIZADO`      TINYINT(1) DEFAULT NULL,
  MODIFY `PELIGROSO`         TINYINT(1) DEFAULT NULL,
  MODIFY `ADIESTRAMIENTO`    TINYINT(1) DEFAULT NULL;

-- Fechas
ALTER TABLE `ANIMALES`
  MODIFY `FECHA_ULTIMA_VACUNACION_ANTIRRABICA` DATE DEFAULT NULL,
  MODIFY `FECHA_EXP` DATE DEFAULT NULL;

-- Año de nacimiento: normalizar los valores que son fecha completa a sólo el año
UPDATE `ANIMALES`
   SET `ANIO_NACIMIENTO` = LEFT(`ANIO_NACIMIENTO`, 4)
 WHERE `ANIO_NACIMIENTO` REGEXP '^[0-9]{4}-';

ALTER TABLE `ANIMALES`
  MODIFY `ANIO_NACIMIENTO` YEAR DEFAULT NULL;

-- Textos cortos
ALTER TABLE `ANIMALES`
  MODIFY `NOMBRE`              VARCHAR(50)  DEFAULT NULL,
  MODIFY `ESPECIE`              VARCHAR(50)  DEFAULT NULL,
  MODIFY `RAZA`                 VARCHAR(80)  DEFAULT NULL,
  MODIFY `COLOR`                VARCHAR(50)  DEFAULT NULL,
  MODIFY `N_CITES`              VARCHAR(50)  DEFAULT NULL,
  MODIFY `SEGURO_COMPANIA`      VARCHAR(80)  DEFAULT NULL,
  MODIFY `SEGURO_POLIZA`        VARCHAR(80)  DEFAULT NULL,
  MODIFY `LUGAR`                VARCHAR(100) DEFAULT NULL,
  MODIFY `N_CERTIFICADO_ADIESTRADOR` VARCHAR(80) DEFAULT NULL,
  MODIFY `DOMICILIO_HABITUAL_ANIMAL` VARCHAR(150) DEFAULT NULL,
  MODIFY `N_CENSO`              VARCHAR(50)  DEFAULT NULL,
  MODIFY `CODIGO_CENSO`         VARCHAR(50)  DEFAULT NULL,
  MODIFY `EXPEDIDA_EN`          VARCHAR(100) DEFAULT NULL;

-- Índice sobre ANIO_NACIMIENTO: ya existía como prefix(4); cambiar a índice completo
ALTER TABLE `ANIMALES` DROP INDEX `idx_anim_anio`;
ALTER TABLE `ANIMALES` ADD  INDEX `idx_anim_anio` (`ANIO_NACIMIENTO`);
ALTER TABLE `ANIMALES` DROP INDEX `idx_anim_especie`;
ALTER TABLE `ANIMALES` ADD  INDEX `idx_anim_especie` (`ESPECIE`);

-- ---------- BAJA_ANIMAL ----------
ALTER TABLE `BAJA_ANIMAL`
  MODIFY `FECHA`  DATE DEFAULT NULL,
  MODIFY `N_BAJA` VARCHAR(50) DEFAULT NULL;
ALTER TABLE `BAJA_ANIMAL` DROP INDEX `idx_baja_fecha`;
ALTER TABLE `BAJA_ANIMAL` ADD  INDEX `idx_baja_fecha` (`FECHA`);

-- ---------- ALTA_ANIMAL ----------
ALTER TABLE `ALTA_ANIMAL`
  MODIFY `FECHA_ALTA` DATE DEFAULT NULL,
  MODIFY `N_ALTA`     VARCHAR(50) DEFAULT NULL;
ALTER TABLE `ALTA_ANIMAL` DROP INDEX `idx_alta_fecha`;
ALTER TABLE `ALTA_ANIMAL` ADD  INDEX `idx_alta_fecha` (`FECHA_ALTA`);

-- ---------- PROPIETARIOS ----------
ALTER TABLE `PROPIETARIOS`
  MODIFY `PRIMER_APELLIDO`  VARCHAR(50) DEFAULT NULL,
  MODIFY `SEGUNDO_APELLIDO` VARCHAR(50) DEFAULT NULL,
  MODIFY `NOMBRE`           VARCHAR(50) DEFAULT NULL,
  MODIFY `TELEFONO1`        VARCHAR(20) DEFAULT NULL,
  MODIFY `TELEFONO2`        VARCHAR(20) DEFAULT NULL,
  MODIFY `DOMICILIO`        VARCHAR(150) DEFAULT NULL,
  MODIFY `CP`               VARCHAR(10)  DEFAULT NULL,
  MODIFY `MUNICIPIO`        VARCHAR(100) DEFAULT NULL;

-- ---------- MOTIVO_BAJA ----------
ALTER TABLE `MOTIVO_BAJA`
  MODIFY `MOTIVO_BAJA` VARCHAR(150) DEFAULT NULL;

-- ---------- ANIMALES_PELIGROSOS ----------
ALTER TABLE `ANIMALES_PELIGROSOS`
  MODIFY `LICENCIA_EXPEDIDA_POR`            VARCHAR(100) DEFAULT NULL,
  MODIFY `FECHA_EXPEDICION_LICENCIA`        DATE         DEFAULT NULL,
  MODIFY `DESTINO_ANIMAL_SI_ES_PERRO_O_GATO` VARCHAR(150) DEFAULT NULL,
  MODIFY `FAMILIA_SI_NO_ES_PERRO_O_GATO`    VARCHAR(100) DEFAULT NULL,
  MODIFY `ESPECIE`                          VARCHAR(50)  DEFAULT NULL,
  MODIFY `IDENTIFICACION`                   VARCHAR(100) DEFAULT NULL,
  MODIFY `HABITACULO`                       VARCHAR(100) DEFAULT NULL,
  MODIFY `ESPECIE_PROTEGIDA`                TINYINT(1)   DEFAULT NULL,
  MODIFY `VENDEDOR`                         VARCHAR(100) DEFAULT NULL,
  MODIFY `N_CENSO`                          VARCHAR(50)  DEFAULT NULL,
  MODIFY `OTROS`                            VARCHAR(255) DEFAULT NULL,
  MODIFY `COD_CENSO`                        VARCHAR(50)  DEFAULT NULL;

SET FOREIGN_KEY_CHECKS=1;
