version: "3.8"

services:
  api:
    build: ./api
    container_name: censo_api
    restart: unless-stopped
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: "3307"
      DB_USER: root
      DB_PASSWORD: "123"
      DB_NAME: censo_animales
      LOG_DIR: /app/logs
      AUTH_FILE: /app/auth.json
    volumes:
      - ./logs:/app/logs
      - ./auth.json:/app/auth.json
    networks:
      - red_censo

  web:
    image: nginx:alpine
    container_name: censo_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - red_censo

networks:
  red_censo:
    driver: bridge