# ── Puerto 80 — Acceso público para empleados ─────────────────────────────────
server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass         http://api:5000/api/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $remote_addr;
        # Forzar a vacío para que un cliente externo no pueda suplantarlo
        proxy_set_header   X-Admin-Access "";
    }
}

# ── Puerto 8080 — Acceso exclusivo para administrador (solo localhost) ─────────
server {
    listen 8080;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass         http://api:5000/api/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $remote_addr;
        # Este header identifica la petición como de administrador
        proxy_set_header   X-Admin-Access "true";
    }
}
